---
name: Device-Cdio
version: v0.2.0
author:
  - Rocky Bernstein <rocky@cpan.org>
abstract: CD Input and control library
license: gpl
requires:
  ExtUtils::PkgConfig: 1.03
  Test::More: 0
  version: 0
provides:
  Device::Cdio:
    file: lib/Device/Cdio.pm
    version: v0.2.0
  Device::Cdio::Device:
    file: lib/Device/Cdio/Device.pm
  Device::Cdio::ISO9660:
    file: lib/Device/Cdio/ISO9660.pm
  Device::Cdio::ISO9660::FS:
    file: lib/Device/Cdio/ISO9660/FS.pm
  Device::Cdio::ISO9660::IFS:
    file: lib/Device/Cdio/ISO9660/IFS.pm
  Device::Cdio::Track:
    file: lib/Device/Cdio/Track.pm
  Device::Cdio::Util:
    file: lib/Device/Cdio/Util.pm
generated_by: Module::Build version 0.2611
