---
abstract: 'Perl bindings for CD Input and control library (libcdio)'
author:
  - 'Rocky Bernstein <rocky@cpan.org>'
build_requires:
  ExtUtils::CBuilder: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Device-Cdio
provides:
  Device::Cdio:
    file: lib/Device/Cdio.pm
    version: v0.3.0
  Device::Cdio::Device:
    file: lib/Device/Cdio/Device.pm
    version: 0
  Device::Cdio::ISO9660:
    file: lib/Device/Cdio/ISO9660.pm
    version: 0
  Device::Cdio::ISO9660::FS:
    file: lib/Device/Cdio/ISO9660/FS.pm
    version: 0
  Device::Cdio::ISO9660::IFS:
    file: lib/Device/Cdio/ISO9660/IFS.pm
    version: 0
  Device::Cdio::Track:
    file: lib/Device/Cdio/Track.pm
    version: 0
  Device::Cdio::Util:
    file: lib/Device/Cdio/Util.pm
    version: 0
  perlcdio:
    file: lib/perlcdio.pm
    version: 0
  perlcdioc:
    file: lib/perlcdio.pm
    version: 0
  perliso9660:
    file: lib/perliso9660.pm
    version: 0
  perliso9660c:
    file: lib/perliso9660.pm
    version: 0
  perlmmc:
    file: lib/perlmmc.pm
    version: 0
  perlmmcc:
    file: lib/perlmmc.pm
    version: 0
requires:
  ExtUtils::CBuilder: 0.28
  ExtUtils::PkgConfig: 1.03
  Test::More: 0
  version: 0
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: v0.3.0
